services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: car_shop_app
    ports:
      - "8000:8000"
    depends_on:
      - db

# Volumes are used to create persistent data storage that is not deleted when the container is restarted or recreated
volumes:
  postgres_data:
